# Generated by Django 3.0.5 on 2020-04-02 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('nrek', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reimburse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('desc', models.TextField(max_length=2000)),
                ('amnt', models.PositiveIntegerField()),
                ('rcpt', models.FileField(upload_to='')),
                ('stat', models.CharField(choices=[('ACC', 'Accepted'), ('REJ', 'Rejected'), ('ONH', 'Onhold'), ('SBM', 'Submitted')], default='SBM', max_length=3)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beReimburse.Employee')),
            ],
        ),
    ]
